name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest 

      - name: push image to docker hub
        run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
         docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
         