name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: echo "IMAGE_NAME=my-web-app" >> $GITHUB_ENV
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
